[package]
name = "json-writer"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.9.0"
regex = "1.10.4"
serde = "1.0.197"
serde_json = "1.0.114"
