[package]
name = "json-writer"
version = "1.0.0"
edition = "2021"

[dependencies]
rayon = "^1.10.0"
serde = "^1.0.197"
serde_json = "^1.0.116"
indexmap = "2.2.6"
colored = "2.1.0"
sys-locale = "0.3.1"
clap = { version = "4.5.7" }
clap_derive = { version = "4.0.0-rc.1" }
