[package]
name = "json-writer"
version = "1.0.0"
edition = "2021"

[dependencies]
rayon = "^1.10.0"
serde = "^1.0.197"
serde_json = "^1.0.116"
indexmap = "2.2.6"
sys-locale = "0.3.1"
clap = { version = "4.5.7", features = ["wrap_help"] }
rand = "0.8.5"
color-print = "0.3.6"
regex = "1.10.5"
